package foundation

type NSAffineTransform struct{}
type NSAppleEventDescriptor struct{}
type NSAppleEventManager struct{}
type NSAppleScript struct{}
type NSArchiver struct{}
type NSArray struct{}
type NSAssertionHandler struct{}
type NSAttributedString struct{}
type NSBackgroundActivityScheduler struct{}
type NSBlockOperation struct{}
type NSBundle struct{}
type NSBundleResourceRequest struct{}
type NSByteCountFormatter struct{}
type NSCache struct{}
type NSCalendar struct{}
type NSCalendarDate struct{}
type NSCharacterSet struct{}
type NSCoder struct{}
type NSComparisonPredicate struct{}
type NSCondition struct{}
type NSConditionLock struct{}
type NSConnection struct{}
type NSData struct{}
type NSDate struct{}
type NSDateComponents struct{}
type NSDateComponentsFormatter struct{}
type NSDateFormatter struct{}
type NSDateInterval struct{}
type NSDecimalNumber struct{}
type NSDecimalNumberHandler struct{}
type NSDictionary struct{}
type NSDistantObject struct{}
type NSDistributedLock struct{}
type NSDistributedNotificationCenter struct{}
type NSEnergyFormatter struct{}
type NSError struct{}
type NSException struct{}
type NSExpression struct{}
type NSExtensionContext struct{}
type NSFileCoordinator struct{}
type NSFileHandle struct{}
type NSFileManager struct{}
type NSFileProviderService struct{}
type NSFileVersion struct{}
type NSFileWrapper struct{}
type NSFormatter struct{}
type NSGarbageCollector struct{}
type NSHTTPCookie struct{}
type NSHTTPCookieStorage struct{}
type NSHashTable struct{}
type NSHost struct{}
type NSIndexPath struct{}
type NSIndexSet struct{}
type NSInputStream struct{}
type NSInvocation struct{}
type NSInvocationOperation struct{}
type NSItemProvider struct{}
type NSJSONSerialization struct{}
type NSKeyedArchiver struct{}
type NSKeyedUnarchiver struct{}
type NSLengthFormatter struct{}
type NSLinguisticTagger struct{}
type NSLocale struct{}
type NSLock struct{}
type NSMachBootstrapServer struct{}
type NSMassFormatter struct{}
type NSMeasurement struct{}
type NSMetadataQuery struct{}
type NSMethodSignature struct{}
type NSMutableArray struct{}
type NSMutableData struct{}
type NSMutableOrderedSet struct{}
type NSMutableString struct{}
type NSMutableURLRequest struct{}
type NSNetService struct{}
type NSNetServiceBrowser struct{}
type NSNotificationCenter struct{}
type NSNumber struct{}
type NSNumberFormatter struct{}
type NSObject struct{}
type NSOperation struct{}
type NSOperationQueue struct{}
type NSOrderedSet struct{}
type NSOutputStream struct{}
type NSPersonNameComponentsFormatter struct{}
type NSPointerArray struct{}
type NSPointerFunctions struct{}
type NSPort struct{}
type NSPortCoder struct{}
type NSPortMessage struct{}
type NSPortNameServer struct{}
type NSPositionalSpecifier struct{}
type NSPredicate struct{}
type NSProcessInfo struct{}
type NSProgress struct{}
type NSPropertyListSerialization struct{}
type NSProtocolChecker struct{}
type NSProxy struct{}
type NSRecursiveLock struct{}
type NSRegularExpression struct{}
type NSRunLoop struct{}
type NSScanner struct{}
type NSScriptClassDescription struct{}
type NSScriptCoercionHandler struct{}
type NSScriptCommand struct{}
type NSScriptCommandDescription struct{}
type NSScriptObjectSpecifier struct{}
type NSScriptWhoseTest struct{}
type NSSet struct{}
type NSSocketPortNameServer struct{}
type NSSortDescriptor struct{}
type NSSpellServer struct{}
type NSStream struct{}
type NSString struct{}
type NSTask struct{}
type NSThread struct{}
type NSTimeZone struct{}
type NSTimer struct{}
type NSURL struct{}
type NSURLCache struct{}
type NSURLComponents struct{}
type NSURLConnection struct{}
type NSURLCredential struct{}
type NSURLCredentialStorage struct{}
type NSURLDownload struct{}
type NSURLHandle struct{}
type NSURLProtectionSpace struct{}
type NSURLProtocol struct{}
type NSURLRequest struct{}
type NSURLSession struct{}
type NSURLSessionConfiguration struct{}
type NSURLSessionDownloadTask struct{}
type NSURLSessionStreamTask struct{}
type NSURLSessionTaskTransactionMetrics struct{}
type NSUbiquitousKeyValueStore struct{}
type NSUnarchiver struct{}
type NSUndoManager struct{}
type NSUserActivity struct{}
type NSUserAppleScriptTask struct{}
type NSUserAutomatorTask struct{}
type NSUserDefaults struct{}
type NSUserNotification struct{}
type NSUserScriptTask struct{}
type NSUserUnixTask struct{}
type NSValue struct{}
type NSValueTransformer struct{}
type NSXMLDTD struct{}
type NSXMLDTDNode struct{}
type NSXMLDocument struct{}
type NSXMLElement struct{}
type NSXMLNode struct{}
type NSXMLParser struct{}
type NSXPCConnection struct{}
type NSXPCInterface struct{}
