package foundation

type NSArchiverCallback interface{}
type NSCacheDelegate interface{}
type NSClassDescriptionPrimitives interface{}
type NSCoderMethods interface{}
type NSCoding interface{}
type NSComparisonMethods interface{}
type NSConnectionDelegate interface{}
type NSCopyLinkMoveHandler interface{}
type NSCopying interface{}
type NSDecimalNumberBehaviors interface{}
type NSDelayedPerforming interface{}
type NSDeprecatedKeyValueCoding interface{}
type NSDeprecatedKeyValueObservingCustomization interface{}
type NSDeprecatedMethods interface{}
type NSDiscardableContent interface{}
type NSDiscardableContentProxy interface{}
type NSDistributedObjects interface{}
type NSErrorRecoveryAttempting interface{}
type NSFastEnumeration interface{}
type NSFileManagerDelegate interface{}
type NSFilePresenter interface{}
type NSKeyValueCoding interface{}
type NSKeyValueObserverNotification interface{}
type NSKeyValueObserverRegistration interface{}
type NSKeyValueObserving interface{}
type NSKeyValueObservingCustomization interface{}
type NSKeyedArchiverDelegate interface{}
type NSKeyedArchiverObjectSubstitution interface{}
type NSKeyedUnarchiverDelegate interface{}
type NSKeyedUnarchiverObjectSubstitution interface{}
type NSLocking interface{}
type NSMachPortDelegate interface{}
type NSMetadataQueryDelegate interface{}
type NSMutableCopying interface{}
type NSNetServiceBrowserDelegate interface{}
type NSNetServiceDelegate interface{}
type NSObject interface{}
type NSPortDelegate interface{}
type NSProgressReporting interface{}
type NSScriptClassDescription interface{}
type NSScriptKeyValueCoding interface{}
type NSScriptObjectSpecifiers interface{}
type NSScripting interface{}
type NSScriptingComparisonMethods interface{}
type NSSecureCoding interface{}
type NSSpellServerDelegate interface{}
type NSStreamDelegate interface{}
type NSThreadPerformAdditions interface{}
type NSURLAuthenticationChallengeSender interface{}
type NSURLClient interface{}
type NSURLConnectionDataDelegate interface{}
type NSURLConnectionDelegate interface{}
type NSURLConnectionDownloadDelegate interface{}
type NSURLDownloadDelegate interface{}
type NSURLHandleClient interface{}
type NSURLProtocolClient interface{}
type NSURLSessionDataDelegate interface{}
type NSURLSessionDelegate interface{}
type NSURLSessionDownloadDelegate interface{}
type NSURLSessionStreamDelegate interface{}
type NSURLSessionTaskDelegate interface{}
type NSUserNotificationCenterDelegate interface{}
type NSXMLParserDelegate interface{}
type NSXPCListenerDelegate interface{}
type NSXPCProxyCreating interface{}
