#!/usr/bin/env node

const { spawn, spawnSync } = require('child_process');
const fs = require("fs");
const ejs = require("ejs");

var electronDev = null;

process.on("SIGINT", () => {
    if (electronDev) {
        spawnSync("kill", ["-9", "-"+electronDev.pid]);
    }
});



(function() {
    console.log("Compiling TypeScript...");
    var tsc = spawnSync('tsc');
    console.log(tsc.stdout.toString('ascii'));
    console.log(tsc.stderr.toString('ascii'));
    if (tsc.status != 0) {
        return;
    }
    electronDev = spawn('./node_modules/.bin/electron', ['./dist/src/main/main.js']);
    electronDev.stdout.on('data', (data) => {
        console.log(data.toString().trimRight());
    });
    electronDev.stderr.on('data', (data) => {
        console.log(data.toString().trimRight());
    });
    electronDev.on('exit', (code) => {
        console.log(`Child exited with code ${code}`);
    });
})();